# Site settings
title: Mario Peña Jr
email: mapg.jr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username: mpjr1
github_username: mpjr1

# Build settings
markdown: kramdown
